<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="ustjava87" failures="0" tests="2" name="com.experitest.auto.AndroidDemoTest" time="0.001" errors="1" timestamp="08 Nov 2021 12:01:10 GMT" skipped="1">
  <testcase classname="com.experitest.auto.AndroidDemoTest" name="setUp" time="0.000">
    <error message="The method lockDeviceForExecution failed with error: &#039;The maximum allowed number of reservations has been exceeded: 2&#039;" type="com.experitest.client.InternalException">
      <![CDATA[com.experitest.client.InternalException: The method lockDeviceForExecution failed with error: 'The maximum allowed number of reservations has been exceeded: 2'
	at com.experitest.client.GridClient.lockDeviceForExecution(GridClient.java:460)
	at com.experitest.client.GridClient.lockDeviceForExecution(GridClient.java:253)
	at com.experitest.auto.BaseTest.init(BaseTest.java:36)
	at com.experitest.auto.AndroidDemoTest.setUp(AndroidDemoTest.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="com.experitest.auto.AndroidDemoTest" name="test" time="0.001">
    <skipped/>
  </testcase> <!-- test -->
</testsuite> <!-- com.experitest.auto.AndroidDemoTest -->
